# Generated by Django 5.0.6 on 2024-06-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khanadotcom_app', '0002_user_login_attempts_failedloginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_attempts',
        ),
    ]
